nit(org-mode): remove duplicate quote snippet
doomemacs/snippets pull request #80
Opened 2022-03-14 15:36 UTC by dschrempf

2022-03-21 15:11 UTC, hlissner requested changes
This snippet is wanted and should not be removed. At the very least, `quote` should be an alias like `begin_src` is for `src`. E.g.

```snippet
# -*- mode: snippet -*-
# name: #+begin_quote block
# key: <q
# uuid: <q
# --
(doom-snippets-expand :uuid "quote")
```

Can you change that instead?

2022-03-23 09:57 UTC, dschrempf commented
This should be done. I also added `# type: command`.

2022-05-03 18:41 UTC, hlissner approved these changes

2022-05-03 19:50 UTC, merged

2022-05-03 19:50 UTC, hlissner commented
Sorry for the tremendously late response. Thanks for your help!